### PR TITLE
Bug correction for xdyn-for-cs

### PR DESCRIPTION
**Pull request by mcharlou**
## Description
Changed the call to `get_StateType` to get the last record of the state history provided by the user instead of the first.

## Related Issue
This corrects Issue #7 

## Motivation and Context
See Issue #7  

## How Has This Been Tested?
Tested with a simple simulation with xdyn-for-cs

### CODE REVIEW

**Comment by Gjacquenot** [comment]
@mcharlou Thanks for this pull requests.
We will look at it closely.

We will cherry-pick your last commit on top of the master branch (You have introduced an empty merge commit).

**Comment by mcharlou** [comment]
@Gjacquenot Very sorry for that... I was actually trying to update my personal fork of xdyn directly on GitHub, but apparently what I did is not the proper way. I don't know of any way to fetch from the original repo to a personal fork directly on GitHub.

**Comment by Gjacquenot** [comment]
You should do something like this

```bash
git remote add github_xdyn https://github.com/sirehna/xdyn
git fetch github_xdyn
git checkout master
git reset --hard github_xdyn/master
```

**Comment by mcharlou** [comment]
Thanks for the advice ! So there is indeed no way to do it cleanly on GitHub itself (browser) ?

**Comment by Gjacquenot** [comment]
I dont know how to do it on GitHub directly. You can delete your repo and create a new fork to be sure to retrieve latest version.

We agree on your PR. Before merging, we would be pleased to add unit test that expose this bug. Do you have something to propose?

**Comment by GuillaumeJacquenot** [comment]
Hello @mcharlou , we have accepted your fix in the master branch (we have cherry-picked your commit)

If you manage to isolate an example or a unit test, we would be glad to integrate it

**Pull request closed without merging**
